version: '2'
services:
    bug_tracker-app:
        image: bug_tracker
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bug_tracker-mysql:3306/bug_tracker?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bug_tracker-mysql:
        extends:
            file: mysql.yml
            service: bug_tracker-mysql
